version: '3'

services:
  webapp:
    container_name: "webapp"
    build: 
      context: .
      dockerfile: Dockerfile.base
    restart: on-failure
    networks:
      - postgres_default
    ports:
      - "8001:8000"
    env_file: .env
    command: npm start
    # command: tail -f /dev/null
 
networks:
  postgres_default:
    external: true