name: PRODUCTION CI/CD

on:
    # push:
    #     branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v4

            - name: Build Docker image
              env:
                  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  USER_NAME: root
                  HOST_NAME: ${{ secrets.HOST_NAME }}

              run: |
                  mkdir -p ~/.ssh
                  echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
                  chmod 700 ~/.ssh/id_rsa
                  eval $(ssh-agent -s)

                  echo "${{secrets.QINI_API_ENV}}" | tr -d '\r' > ./.env

                  ssh -tt root@45.251.114.243

                  rsync -avzr --delete -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ./ $USER_NAME@$HOST_NAME:/apps/qini-api
                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
