name: PRODUCTION CI/CD

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v3

            - name: Build Docker image
              run: |
                echo "${{secrets.QINI_API_ENV}}" | tr -d '\r' > ./.env
                cat ./.env
            #   run: |
            #       docker-compose up -d --build
            #   docker rmi $(docker images --filter "dangling=true" -q --no-trunc) #remove image danglin
