name: deploy-via-docker-compose

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repository
      uses: actions/checkout@v3
    
    - name: Deploy
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER_NAME: root
          HOST_NAME: ${{ secrets.DEPLOY_SRV_IP }}
      run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          rsync -avzr --delete -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' ./ $USER_NAME@$HOST_NAME:/webapps/hikari-backend
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER_NAME@$HOST_NAME "cd /webapps/hikari-backend && cp /webapps/environment/hikari-backend/.env /webapps/hikari-backend/ && docker-compose up -d --build"