name: PRODUCTION CI/CD

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: production

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v3

            - name: Build Docker image
              env:
                  PORT: ${{ secrets.PORT }}
                  PORT2: ${{ vars.PORT2 }}
                  SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}

                  POSTGRES_IMAGE: ${{ secrets.POSTGRES_IMAGE }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
                  POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

                  APP_IMAGE: ${{ secrets.APP_IMAGE }}
                  APP_NAME: ${{ secrets.APP_NAME }}
                  APP_PORT: ${{ secrets.APP_PORT }}

                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  PRODUCTION_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
              run: echo Building Docker image secret $PORT - vars $PORT2
            #   run: |
            #       docker-compose up -d --build
            #   docker rmi $(docker images --filter "dangling=true" -q --no-trunc) #remove image danglin
